"use client"
import SessionAuthProvider from '@/context/SessionAuthProvider'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ApolloProvider } from '@apollo/client'
import client from '@/config/apollo-client'

const inter = Inter({ subsets: ['latin'] })
/*
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <SessionAuthProvider>
          <ApolloProvider client={client}>
          {children}
          </ApolloProvider>
        </SessionAuthProvider>
      </body>
    </html>
  )
}
